# assumption: Travis build runs in bash 4.0 (or greater)

language: python

before_script:
  - sudo apt-get install --no-install-recommends -y libxml2-utils
  - chmod +x *.sh

script:
  - ./xmlvalidator.sh
  - ./jsonvalidator.sh

notifications:
  email: false
